name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

env:
  REACT_APP_API_URL: https://as-app-dev-cin-01-hbhdegc5bqddaga7.centralindia-01.azurewebsites.net/api
  REACT_APP_AZURE_FUNCTION_URL: https://func-app-dev-01-cuh6h4erhdazb9g6.centralindia-01.azurewebsites.net/api/orders


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
#--------------------- NODE -----------------------------
     
      - name: Install node dependencies
        run: |
          cd app-node-service
          npm ci

#------------------- REACT ---------------------
      - name: Install react dependencies
        run: |
          cd react-typescript
          npm ci

      - name: Build react app
        run: |
          cd react-typescript
          npm run build

      - name: Copy React build to Node public folder
        run: |
          rm -rf app-node-service/public
          mkdir -p app-node-service/public
          cp -r react-typescript/build/* app-node-service/public/

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: as-app-dev-cin-01
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: app-node-service